package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/qtaghdi/xlsx-viewer/internal/workbook"
	"github.com/xuri/excelize/v2"
)

const (
	stdioHelperEnv     = "XLSX_VIEWER_STDIO_HELPER"
	stdioHelperFileEnv = "XLSX_VIEWER_STDIO_FILE"
)

func TestMain(m *testing.M) {
	if os.Getenv(stdioHelperEnv) == "1" {
		runStdioHelper()
		return
	}
	os.Exit(m.Run())
}

func runStdioHelper() {
	session, err := workbook.Open(os.Getenv(stdioHelperFileEnv))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer session.Close()
	if err := NewWithTokens(session, "", "").RunStdio(context.Background()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func TestEmbeddedUIRequiresSessionAndServesAssets(t *testing.T) {
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	if err := file.Close(); err != nil {
		t.Fatal(err)
	}

	session, err := workbook.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	handler := New(session, "test-token").Handler()

	unauthorized := httptest.NewRecorder()
	handler.ServeHTTP(unauthorized, httptest.NewRequest(http.MethodGet, "/", nil))
	if unauthorized.Code != http.StatusUnauthorized {
		t.Fatalf("GET / without session = %d, want %d", unauthorized.Code, http.StatusUnauthorized)
	}

	index := httptest.NewRecorder()
	indexRequest := httptest.NewRequest(http.MethodGet, "/", nil)
	indexRequest.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "test-token"})
	handler.ServeHTTP(index, indexRequest)
	if index.Code != http.StatusOK {
		t.Fatalf("GET / with session = %d, want %d", index.Code, http.StatusOK)
	}
	if !strings.Contains(index.Body.String(), "Workbook editor") {
		t.Fatal("embedded UI is missing the workbook editor")
	}

	assetPath := findJavaScriptAsset(index.Body.String())
	if assetPath == "" {
		t.Fatal("embedded UI does not reference a JavaScript asset")
	}
	assets, err := fs.Glob(staticFS, "static/assets/*.js")
	if err != nil {
		t.Fatal(err)
	}
	if len(assets) == 0 {
		t.Skip("frontend assets are generated by pnpm --dir web run build")
	}

	asset := httptest.NewRecorder()
	assetRequest := httptest.NewRequest(http.MethodGet, assetPath, nil)
	assetRequest.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "test-token"})
	handler.ServeHTTP(asset, assetRequest)
	if asset.Code != http.StatusOK {
		t.Fatalf("GET %s with session = %d, want %d", assetPath, asset.Code, http.StatusOK)
	}
	if !strings.Contains(asset.Header().Get("Content-Type"), "javascript") {
		t.Fatalf("asset content type = %q, want JavaScript", asset.Header().Get("Content-Type"))
	}
}

func TestMCPAppToolAndResource(t *testing.T) {
	if _, err := staticFS.ReadFile("static/app.html"); err != nil {
		t.Skip("MCP App bundle is generated by pnpm --dir web run build")
	}
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	_ = file.Close()

	session, err := workbook.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	server := NewWithTokens(session, "browser-token", "mcp-token").mcpServer()
	client := mcp.NewClient(&mcp.Implementation{Name: "test-client", Version: "0.1.0"}, nil)
	serverTransport, clientTransport := mcp.NewInMemoryTransports()
	serverSession, err := server.Connect(context.Background(), serverTransport, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer serverSession.Close()
	clientSession, err := client.Connect(context.Background(), clientTransport, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer clientSession.Close()
	if got := clientSession.InitializeResult().Instructions; got != serverInstructions {
		t.Fatalf("server instructions = %q, want %q", got, serverInstructions)
	}

	tools, err := clientSession.ListTools(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	var openTool *mcp.Tool
	for _, tool := range tools.Tools {
		if tool.Name == "open_workbook" {
			openTool = tool
			break
		}
	}
	if openTool == nil {
		t.Fatal("open_workbook tool is not registered")
	}
	ui, ok := openTool.Meta["ui"].(map[string]any)
	if !ok || ui["resourceUri"] != appResourceURI {
		t.Fatalf("open_workbook UI metadata = %#v", openTool.Meta)
	}
	if openTool.Meta["openai/outputTemplate"] != appResourceURI {
		t.Fatalf("open_workbook compatibility metadata = %#v", openTool.Meta)
	}

	resource, err := clientSession.ReadResource(context.Background(), &mcp.ReadResourceParams{URI: appResourceURI})
	if err != nil {
		t.Fatal(err)
	}
	if len(resource.Contents) != 1 || resource.Contents[0].MIMEType != "text/html;profile=mcp-app" {
		t.Fatalf("MCP App resource = %#v", resource.Contents)
	}
	if !strings.Contains(resource.Contents[0].Text, "Workbook editor") {
		t.Fatal("MCP App resource is missing the workbook editor")
	}
}

func TestStdioTransport(t *testing.T) {
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SetCellValue("Sheet1", "A1", "stdio"); err != nil {
		t.Fatal(err)
	}
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	if err := file.Close(); err != nil {
		t.Fatal(err)
	}

	command := exec.Command(os.Args[0])
	command.Env = append(os.Environ(), stdioHelperEnv+"=1", stdioHelperFileEnv+"="+path)
	client := mcp.NewClient(&mcp.Implementation{Name: "stdio-test-client", Version: "0.1.0"}, nil)
	clientSession, err := client.Connect(context.Background(), &mcp.CommandTransport{Command: command}, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer clientSession.Close()

	if got := clientSession.InitializeResult().Instructions; got != serverInstructions {
		t.Fatalf("stdio server instructions = %q, want %q", got, serverInstructions)
	}
	result, err := clientSession.CallTool(context.Background(), &mcp.CallToolParams{Name: "read_range", Arguments: map[string]any{
		"sheet": "Sheet1",
		"range": "A1",
	}})
	if err != nil {
		t.Fatal(err)
	}
	if result.IsError || result.StructuredContent == nil {
		t.Fatalf("stdio read_range result = %#v", result)
	}
	structured, err := json.Marshal(result.StructuredContent)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(structured, []byte(`"stdio"`)) {
		t.Fatalf("stdio read_range structured content = %s", structured)
	}
}

func findJavaScriptAsset(index string) string {
	const prefix = `/assets/`
	start := strings.Index(index, prefix)
	if start == -1 {
		return ""
	}
	end := strings.Index(index[start:], `.js`)
	if end == -1 {
		return ""
	}
	return index[start : start+end+len(`.js`)]
}

func TestBrowserAndMCPUseSeparateTokens(t *testing.T) {
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	_ = file.Close()

	session, err := workbook.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()
	handler := NewWithTokens(session, "browser-token", "mcp-token").Handler()

	presence := httptest.NewRecorder()
	presenceRequest := httptest.NewRequest(http.MethodPost, "/api/presence", bytes.NewBufferString(`{"sheet":"Sheet1","range":"A1:B2","state":"selecting"}`))
	presenceRequest.Header.Set("Content-Type", "application/json")
	presenceRequest.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "browser-token"})
	handler.ServeHTTP(presence, presenceRequest)
	if presence.Code != http.StatusNoContent {
		t.Fatalf("POST /api/presence = %d, want %d: %s", presence.Code, http.StatusNoContent, presence.Body.String())
	}

	wrongMCP := httptest.NewRecorder()
	wrongMCPRequest := httptest.NewRequest(http.MethodPost, "/mcp", nil)
	wrongMCPRequest.Header.Set("Authorization", "Bearer browser-token")
	handler.ServeHTTP(wrongMCP, wrongMCPRequest)
	if wrongMCP.Code != http.StatusUnauthorized {
		t.Fatalf("MCP with browser token = %d, want %d", wrongMCP.Code, http.StatusUnauthorized)
	}

	mcp := httptest.NewRecorder()
	mcpRequest := httptest.NewRequest(http.MethodPost, "/mcp", bytes.NewBufferString(`{}`))
	mcpRequest.Header.Set("Authorization", "Bearer mcp-token")
	mcpRequest.Header.Set("Content-Type", "application/json")
	handler.ServeHTTP(mcp, mcpRequest)
	if mcp.Code == http.StatusUnauthorized {
		t.Fatal("MCP token was rejected")
	}
}
