package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/qtaghdi/document-workspace/internal/formats/xlsx"
	"github.com/xuri/excelize/v2"
)

const (
	stdioHelperEnv     = "DOCUMENT_WORKSPACE_STDIO_HELPER"
	stdioHelperFileEnv = "DOCUMENT_WORKSPACE_STDIO_FILE"
	stdioBrowserEnv    = "DOCUMENT_WORKSPACE_STDIO_BROWSER"
)

func TestMain(m *testing.M) {
	if os.Getenv(stdioHelperEnv) == "1" {
		runStdioHelper()
		return
	}
	os.Exit(m.Run())
}

func runStdioHelper() {
	session, err := xlsx.Open(os.Getenv(stdioHelperFileEnv))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer session.Close()
	server := NewWithTokens(session, "browser-token", "mcp-token")
	if os.Getenv(stdioBrowserEnv) == "1" {
		err = server.RunStdioWithBrowser(context.Background(), "127.0.0.1:0")
	} else {
		err = server.RunStdio(context.Background())
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func TestEmbeddedUIRequiresSessionAndServesAssets(t *testing.T) {
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	if err := file.Close(); err != nil {
		t.Fatal(err)
	}

	session, err := xlsx.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	handler := New(session, "test-token").Handler()

	unauthorized := httptest.NewRecorder()
	handler.ServeHTTP(unauthorized, httptest.NewRequest(http.MethodGet, "/", nil))
	if unauthorized.Code != http.StatusUnauthorized {
		t.Fatalf("GET / without session = %d, want %d", unauthorized.Code, http.StatusUnauthorized)
	}

	index := httptest.NewRecorder()
	indexRequest := httptest.NewRequest(http.MethodGet, "/", nil)
	indexRequest.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "test-token"})
	handler.ServeHTTP(index, indexRequest)
	if index.Code != http.StatusOK {
		t.Fatalf("GET / with session = %d, want %d", index.Code, http.StatusOK)
	}
	if !strings.Contains(index.Body.String(), "Workbook editor") {
		t.Fatal("embedded UI is missing the workbook editor")
	}

	assetPath := findJavaScriptAsset(index.Body.String())
	if assetPath == "" {
		t.Fatal("embedded UI does not reference a JavaScript asset")
	}
	assets, err := fs.Glob(staticFS, "static/assets/*.js")
	if err != nil {
		t.Fatal(err)
	}
	if len(assets) == 0 {
		t.Skip("frontend assets are generated by pnpm --dir apps/web-editor run build")
	}

	asset := httptest.NewRecorder()
	assetRequest := httptest.NewRequest(http.MethodGet, assetPath, nil)
	assetRequest.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "test-token"})
	handler.ServeHTTP(asset, assetRequest)
	if asset.Code != http.StatusOK {
		t.Fatalf("GET %s with session = %d, want %d", assetPath, asset.Code, http.StatusOK)
	}
	if !strings.Contains(asset.Header().Get("Content-Type"), "javascript") {
		t.Fatalf("asset content type = %q, want JavaScript", asset.Header().Get("Content-Type"))
	}
}

func TestMCPAppToolAndResource(t *testing.T) {
	if _, err := staticFS.ReadFile("static/app.html"); err != nil {
		t.Skip("MCP App bundle is generated by pnpm --dir apps/web-editor run build")
	}
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	_ = file.Close()

	session, err := xlsx.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	api := NewWithTokens(session, "browser-token", "mcp-token")
	api.launchMu.Lock()
	api.browserBaseURL = "http://127.0.0.1:54321"
	api.launchMu.Unlock()
	server := api.mcpServer()
	client := mcp.NewClient(&mcp.Implementation{Name: "test-client", Version: "0.1.0"}, nil)
	serverTransport, clientTransport := mcp.NewInMemoryTransports()
	serverSession, err := server.Connect(context.Background(), serverTransport, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer serverSession.Close()
	clientSession, err := client.Connect(context.Background(), clientTransport, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer clientSession.Close()
	if got := clientSession.InitializeResult().Instructions; got != serverInstructions {
		t.Fatalf("server instructions = %q, want %q", got, serverInstructions)
	}

	tools, err := clientSession.ListTools(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	var openTool *mcp.Tool
	for _, tool := range tools.Tools {
		if tool.Name == "open_workbook" {
			openTool = tool
			break
		}
	}
	if openTool == nil {
		t.Fatal("open_workbook tool is not registered")
	}
	ui, ok := openTool.Meta["ui"].(map[string]any)
	if !ok || ui["resourceUri"] != appResourceURI {
		t.Fatalf("open_workbook UI metadata = %#v", openTool.Meta)
	}
	if openTool.Meta["openai/outputTemplate"] != appResourceURI {
		t.Fatalf("open_workbook compatibility metadata = %#v", openTool.Meta)
	}
	openResult, err := clientSession.CallTool(context.Background(), &mcp.CallToolParams{Name: "open_workbook"})
	if err != nil {
		t.Fatal(err)
	}
	encodedOpenResult, err := json.Marshal(openResult.StructuredContent)
	if err != nil {
		t.Fatal(err)
	}
	var opened openWorkbookResponse
	if err := json.Unmarshal(encodedOpenResult, &opened); err != nil {
		t.Fatal(err)
	}
	if opened.Name != "book.xlsx" || opened.BrowserURL == "" {
		t.Fatalf("open_workbook result = %#v", opened)
	}
	if strings.Contains(opened.BrowserURL, "browser-token") {
		t.Fatal("open_workbook exposed the reusable browser token")
	}
	launchURL, err := url.Parse(opened.BrowserURL)
	if err != nil {
		t.Fatal(err)
	}
	launchResponse := httptest.NewRecorder()
	api.Handler().ServeHTTP(launchResponse, httptest.NewRequest(http.MethodGet, launchURL.RequestURI(), nil))
	if launchResponse.Code != http.StatusSeeOther || len(launchResponse.Result().Cookies()) != 1 {
		t.Fatalf("launch response = %d, cookies = %#v", launchResponse.Code, launchResponse.Result().Cookies())
	}
	launchCookie := launchResponse.Result().Cookies()[0]
	if launchCookie.Value != "browser-token" || !launchCookie.HttpOnly || launchCookie.SameSite != http.SameSiteStrictMode {
		t.Fatalf("launch cookie = %#v", launchCookie)
	}
	reusedResponse := httptest.NewRecorder()
	api.Handler().ServeHTTP(reusedResponse, httptest.NewRequest(http.MethodGet, launchURL.RequestURI(), nil))
	if reusedResponse.Code != http.StatusUnauthorized {
		t.Fatalf("reused launch response = %d, want %d", reusedResponse.Code, http.StatusUnauthorized)
	}

	resource, err := clientSession.ReadResource(context.Background(), &mcp.ReadResourceParams{URI: appResourceURI})
	if err != nil {
		t.Fatal(err)
	}
	if len(resource.Contents) != 1 || resource.Contents[0].MIMEType != "text/html;profile=mcp-app" {
		t.Fatalf("MCP App resource = %#v", resource.Contents)
	}
	if !strings.Contains(resource.Contents[0].Text, "Workbook editor") {
		t.Fatal("MCP App resource is missing the workbook editor")
	}
}

func TestStdioTransport(t *testing.T) {
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SetCellValue("Sheet1", "A1", "stdio"); err != nil {
		t.Fatal(err)
	}
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	if err := file.Close(); err != nil {
		t.Fatal(err)
	}

	command := exec.Command(os.Args[0])
	command.Env = append(os.Environ(), stdioHelperEnv+"=1", stdioHelperFileEnv+"="+path, stdioBrowserEnv+"=1")
	command.Stderr = os.Stderr
	client := mcp.NewClient(&mcp.Implementation{Name: "stdio-test-client", Version: "0.1.0"}, nil)
	clientSession, err := client.Connect(context.Background(), &mcp.CommandTransport{Command: command}, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer clientSession.Close()

	if got := clientSession.InitializeResult().Instructions; got != serverInstructions {
		t.Fatalf("stdio server instructions = %q, want %q", got, serverInstructions)
	}
	result, err := clientSession.CallTool(context.Background(), &mcp.CallToolParams{Name: "read_range", Arguments: map[string]any{
		"sheet": "Sheet1",
		"range": "A1",
	}})
	if err != nil {
		t.Fatal(err)
	}
	if result.IsError || result.StructuredContent == nil {
		t.Fatalf("stdio read_range result = %#v", result)
	}
	structured, err := json.Marshal(result.StructuredContent)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(structured, []byte(`"stdio"`)) {
		t.Fatalf("stdio read_range structured content = %s", structured)
	}
	openResult, err := clientSession.CallTool(context.Background(), &mcp.CallToolParams{Name: "open_workbook"})
	if err != nil {
		t.Fatal(err)
	}
	encodedOpenResult, err := json.Marshal(openResult.StructuredContent)
	if err != nil {
		t.Fatal(err)
	}
	var opened openWorkbookResponse
	if err := json.Unmarshal(encodedOpenResult, &opened); err != nil {
		t.Fatal(err)
	}
	launchURL, err := url.Parse(opened.BrowserURL)
	if err != nil || launchURL.Scheme != "http" || launchURL.Hostname() != "127.0.0.1" {
		t.Fatalf("stdio browser URL = %q, parse error = %v", opened.BrowserURL, err)
	}
	noRedirect := &http.Client{CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	launchResponse, err := noRedirect.Get(opened.BrowserURL)
	if err != nil {
		t.Fatal(err)
	}
	_ = launchResponse.Body.Close()
	if launchResponse.StatusCode != http.StatusSeeOther {
		t.Fatalf("stdio browser launch = %d, want %d", launchResponse.StatusCode, http.StatusSeeOther)
	}
}

func TestStdioBrowserRequiresLoopback(t *testing.T) {
	for _, addr := range []string{"0.0.0.0:0", ":0", "192.0.2.1:0"} {
		if err := requireLoopbackAddress(addr); err == nil {
			t.Fatalf("requireLoopbackAddress(%q) succeeded", addr)
		}
	}
	for _, addr := range []string{"127.0.0.1:0", "localhost:0", "[::1]:0"} {
		if err := requireLoopbackAddress(addr); err != nil {
			t.Fatalf("requireLoopbackAddress(%q) = %v", addr, err)
		}
	}
}

func TestBrowserLaunchLinksAreBounded(t *testing.T) {
	server := &Server{
		browserBaseURL: "http://127.0.0.1:54321",
		launchTokens:   make(map[string]time.Time),
	}
	server.launchTokens["expired"] = time.Now().Add(-time.Second)
	if _, err := server.issueBrowserLaunchURL(); err != nil {
		t.Fatal(err)
	}
	if _, exists := server.launchTokens["expired"]; exists {
		t.Fatal("expired launch token was not pruned")
	}
	server.launchTokens = make(map[string]time.Time, maxLaunchTokens)
	for index := range maxLaunchTokens {
		server.launchTokens[fmt.Sprintf("token-%d", index)] = time.Now().Add(time.Minute)
	}
	if _, err := server.issueBrowserLaunchURL(); err == nil {
		t.Fatal("launch URL was issued after reaching the outstanding-token limit")
	}
}

func findJavaScriptAsset(index string) string {
	const prefix = `/assets/`
	start := strings.Index(index, prefix)
	if start == -1 {
		return ""
	}
	end := strings.Index(index[start:], `.js`)
	if end == -1 {
		return ""
	}
	return index[start : start+end+len(`.js`)]
}

func TestBrowserAndMCPUseSeparateTokens(t *testing.T) {
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	_ = file.Close()

	session, err := xlsx.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()
	handler := NewWithTokens(session, "browser-token", "mcp-token").Handler()

	presence := httptest.NewRecorder()
	presenceRequest := httptest.NewRequest(http.MethodPost, "/api/presence", bytes.NewBufferString(`{"sheet":"Sheet1","range":"A1:B2","state":"selecting"}`))
	presenceRequest.Header.Set("Content-Type", "application/json")
	presenceRequest.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "browser-token"})
	handler.ServeHTTP(presence, presenceRequest)
	if presence.Code != http.StatusNoContent {
		t.Fatalf("POST /api/presence = %d, want %d: %s", presence.Code, http.StatusNoContent, presence.Body.String())
	}

	wrongMCP := httptest.NewRecorder()
	wrongMCPRequest := httptest.NewRequest(http.MethodPost, "/mcp", nil)
	wrongMCPRequest.Header.Set("Authorization", "Bearer browser-token")
	handler.ServeHTTP(wrongMCP, wrongMCPRequest)
	if wrongMCP.Code != http.StatusUnauthorized {
		t.Fatalf("MCP with browser token = %d, want %d", wrongMCP.Code, http.StatusUnauthorized)
	}

	mcp := httptest.NewRecorder()
	mcpRequest := httptest.NewRequest(http.MethodPost, "/mcp", bytes.NewBufferString(`{}`))
	mcpRequest.Header.Set("Authorization", "Bearer mcp-token")
	mcpRequest.Header.Set("Content-Type", "application/json")
	handler.ServeHTTP(mcp, mcpRequest)
	if mcp.Code == http.StatusUnauthorized {
		t.Fatal("MCP token was rejected")
	}
}

func TestBrowserReadsBoundedSheetObjects(t *testing.T) {
	path := filepath.Join("..", "..", "..", "testdata", "xlsx", "compatibility", "feature-rich.xlsx")
	session, err := xlsx.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()
	handler := NewWithTokens(session, "browser-token", "mcp-token").Handler()

	response := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodGet, "/api/sheet-objects?sheet=Compatibility", nil)
	request.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "browser-token"})
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("GET /api/sheet-objects = %d, want %d: %s", response.Code, http.StatusOK, response.Body.String())
	}
	var objects xlsx.SheetObjects
	if err := json.NewDecoder(response.Body).Decode(&objects); err != nil {
		t.Fatal(err)
	}
	if len(objects.Images) != 1 || len(objects.Charts) != 1 {
		t.Fatalf("sheet objects = %#v", objects)
	}
}

func TestBrowserAndMCPShareRevisionedWorkbookSession(t *testing.T) {
	path := filepath.Join(t.TempDir(), "book.xlsx")
	file := excelize.NewFile()
	if err := file.SaveAs(path); err != nil {
		t.Fatal(err)
	}
	if err := file.Close(); err != nil {
		t.Fatal(err)
	}

	session, err := xlsx.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()
	api := NewWithTokens(session, "browser-token", "mcp-token")

	humanWrite := httptest.NewRecorder()
	humanRequest := httptest.NewRequest(http.MethodPost, "/api/operations", bytes.NewBufferString(`{
		"baseRevision": 1,
		"operations": [{"type":"set_cell","sheet":"Sheet1","cell":"F15","value":"Human committed"}]
	}`))
	humanRequest.Header.Set("Content-Type", "application/json")
	humanRequest.Header.Set("Origin", "http://example.com")
	humanRequest.Host = "example.com"
	humanRequest.AddCookie(&http.Cookie{Name: "xlsx_session", Value: "browser-token"})
	api.Handler().ServeHTTP(humanWrite, humanRequest)
	if humanWrite.Code != http.StatusOK {
		t.Fatalf("browser write = %d, want %d: %s", humanWrite.Code, http.StatusOK, humanWrite.Body.String())
	}
	var humanResponse applyResponse
	if err := json.NewDecoder(humanWrite.Body).Decode(&humanResponse); err != nil {
		t.Fatal(err)
	}
	if humanResponse.Workbook.Revision != 2 {
		t.Fatalf("browser revision = %d, want 2", humanResponse.Workbook.Revision)
	}

	mcpServer := api.mcpServer()
	client := mcp.NewClient(&mcp.Implementation{Name: "collaboration-test", Version: "0.1.0"}, nil)
	serverTransport, clientTransport := mcp.NewInMemoryTransports()
	serverSession, err := mcpServer.Connect(context.Background(), serverTransport, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer serverSession.Close()
	clientSession, err := client.Connect(context.Background(), clientTransport, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer clientSession.Close()

	if _, err := clientSession.CallTool(context.Background(), &mcp.CallToolParams{
		Name: "update_presence",
		Arguments: map[string]any{
			"sheet": "Sheet1",
			"range": "C3",
			"state": "editing",
		},
	}); err != nil {
		t.Fatal(err)
	}
	aiWrite, err := clientSession.CallTool(context.Background(), &mcp.CallToolParams{
		Name: "apply_operations",
		Arguments: map[string]any{
			"baseRevision": float64(2),
			"operations": []map[string]any{{
				"type":  "set_cell",
				"sheet": "Sheet1",
				"cell":  "C3",
				"value": "AI committed",
			}},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	encodedAIWrite, err := json.Marshal(aiWrite.StructuredContent)
	if err != nil {
		t.Fatal(err)
	}
	var aiResponse applyResponse
	if err := json.Unmarshal(encodedAIWrite, &aiResponse); err != nil {
		t.Fatal(err)
	}
	if aiResponse.Workbook.Revision != 3 {
		t.Fatalf("AI revision = %d, want 3", aiResponse.Workbook.Revision)
	}

	events, snapshot := session.EventsAfter(0)
	if snapshot.Revision != 3 {
		t.Fatalf("shared session revision = %d, want 3", snapshot.Revision)
	}
	if len(events) != 7 {
		t.Fatalf("event count = %d, want 7: %#v", len(events), events)
	}
	for index, event := range events {
		if event.Sequence != uint64(index+1) {
			t.Fatalf("event %d sequence = %d, want %d", index, event.Sequence, index+1)
		}
	}
	if events[0].Actor != "human" || events[0].Type != "presence.update" || events[2].Type != "cell.commit" || events[2].Revision != 2 {
		t.Fatalf("human events = %#v", events[:3])
	}
	if events[3].Actor != "ai" || events[3].Type != "presence.update" || events[3].Revision != 2 {
		t.Fatalf("AI presence event = %#v", events[3])
	}
	if events[4].Actor != "ai" || events[4].Type != "presence.update" || events[6].Type != "cell.commit" || events[6].Revision != 3 {
		t.Fatalf("AI write events = %#v", events[4:])
	}

	reopened, err := excelize.OpenFile(path)
	if err != nil {
		t.Fatal(err)
	}
	defer reopened.Close()
	for cell, want := range map[string]string{"F15": "Human committed", "C3": "AI committed"} {
		got, err := reopened.GetCellValue("Sheet1", cell)
		if err != nil {
			t.Fatal(err)
		}
		if got != want {
			t.Fatalf("%s = %q, want %q", cell, got, want)
		}
	}
}
